### ISSUE TITLE
Redirect on email Verification

### ISSUE THREAD

**Issue by melvin78** [garethredfern/laravel-vue#15]
Am kind of stuck on how you were able to handle email Verification once the user clicks on the link that eill be sent to his email. I am using nuxt so once i clik on verify email from my browser it redirects me to home which is in the backend instead of frontend. I know i have to change VerifyController.php to return a json response instead of a redirect but where should i start from.

**Comment by garethredfern** [comment]
Hi @melvin78 sorry I missed this issue/question. Have you seen https://laravelvuespa.com/authentication/laravel-authentication#setting-up-fortify the first part explain that you can change the home page that you are redirected to in your config/fortify.php file. Here you can add something like this:

```
'home' => env('SPA_URL') . '/dashboard',
```

In your .env make sure you add `SPA_URL=http://localhost:3000` change the URL to your local URL.

**Comment by melvin78** [comment]
Unfortunately i tried all methods to redirect user back to the SPA url but it doesn't work. Once the user clicks on the verification email link that is sent to the email after registration, there is no way in which the user can be redirected back to the SPA url. Even after changing .env variable to point your frontend.

**Comment by garethredfern** [comment]
What do you have in your fortify config? it should look like this: https://github.com/garethredfern/laravel-api/blob/main/config/fortify.php#L64
