### ISSUE TITLE
Add a license to a repository

### ISSUE THREAD

**Issue by slava-arapov** [garethredfern/laravel-vue#17]
Hi @garethredfern.

I am making a starter for my Laravel+Vue projects and I used your laravelvuespa.com manual so I used your code.

Can I use structure of your projects and code parts in commercial and open source projects? If so, could you add the license to your repositories?

GitHub License Guide: https://choosealicense.com

P.S. Thanks for your work. laravelvuespa.com is the best documentation for Laravel+Vue projects I have seen. 🚀

**Comment by garethredfern** [comment]
Hi @slava-arapov I am please you found the project useful, feel free to use the example codebase in any of your projects. I have added a license.
