### ISSUE TITLE
Automatic redirect to /login from uncached browser window

### ISSUE THREAD

**Issue by marknuyens** [garethredfern/laravel-vue#8]
When you visit [https://laravelvuespa.app](url) in a new incognito tab or try to navigate to the Register page from the /login page using the "Register" button, it automatically redirects back to the /login page, within a few milliseconds. This may be due to the guest middleware. I personally don't use the Register page in my projects, therefore I haven't looked into the issue more detailed.

**Comment by garethredfern** [comment]
Thank you @marknuyens for your pull requests and testing. I have a fix in place for this, please see: https://github.com/garethredfern/laravel-vue/pull/10
